### ISSUE TITLE
数据库命令报错

### ISSUE THREAD

**Issue by yzh990918** [Haixiang6123/nest-todo#1]
![image](https://user-images.githubusercontent.com/46418596/130348978-ab7db409-fccd-4396-a89a-2fc7f5e88573.png)

可能我对mariadb不太熟，但是按照你的教程遇到点问题

**Comment by haixiangyan** [comment]
我了个老天鹅，README.md 写错了，应该是这个命令来做数据库迁移

```shell
npm run migration:run
```

**Comment by haixiangyan** [comment]
如果没有问题，我就 close 啦

**Comment by yzh990918** [comment]
感谢大佬，最近也在学习nest，非常适合练手
