### ISSUE TITLE
在线Demo 提交新todo项会报错

### ISSUE THREAD

**Issue by zhangpeng2k** [Haixiang6123/nest-todo#2]
![image](https://user-images.githubusercontent.com/32725281/131792340-a6a46556-15c5-40c7-9f37-ece1744fd8d4.png)

**Comment by haixiangyan** [comment]
提交的标题和内容是什么呢？

**Comment by Hujianboo** [comment]
提交的标题应该是中文字符吧？ 接口里看了下标题规定只能是英文和数字

**Comment by Hujianboo** [comment]
> 提交的标题和内容是什么呢？

https://github.com/haixiangyan/nest-todo/blob/6a0a41d180db590fb37176b09f90faf65dd114cb/server/src/main.ts#L43
建议交换一下两个过滤器的前后位置,400报错情况下后一个过滤器覆盖了前者，并且其没有报错message信息
